# Generated by Django 4.1.7 on 2023-05-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='departureDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
