# Generated by Django 4.1.7 on 2023-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_flights_departuredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedflights',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
